# P2 - Continuous Control

---

In this notebook, I will describe my solution to the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Learning Algorithm.

I have chosen the multi-agent version of the problem, as I wanted to apply A3C (Asynchronous Advantage Actor Critic) to it. Using this multi-agent approach, we also remove the need to use a replay memory, as the model is getting its uncorrelated data from the various agents that are trying to solve the problem at once. This sounded like a better approach to being able to apply any solution like this to my field of work (AAA videogame industry).


### 2. Implementation



In [1]:
from unityagents import UnityEnvironment
import numpy as np
from agent import AgentOverlord

# Initialize the environment - please note we're using v2 of the problem (multiple agents)
env = UnityEnvironment( file_name='Reacher_Windows_x86_64/Reacher.exe' )

# Get brain - this will be used to control the unity environment
brain_name = env.brain_names[ 0 ]
brain = env.brains[ brain_name ]

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


#### 2.1. Agent initialization

From the description of the problem, we know that:

> "In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible. 
The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`."

With this information, let's initialize our agents and get prepared to solve the problem (in this implementation, we are actually adding an "agent overlord" that will keep track of all of our agents).


In [2]:
# reset the environment
env_info = env.reset(train_mode=False)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]

agent_num = states.shape[ 0 ]

# hyperparameters
actor_layer_size=128
critic_layer_size = 128
gamma = 0.99
learning_rate=5e-4

# initialize overlord
agent_overlord = AgentOverlord( state_size, action_size, agent_num, actor_layer_size, critic_layer_size, gamma, learning_rate )


Number of agents: 20
Size of each action: 4


### 3. Solve the problem

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [3]:
# let's restart the environment and get the initial states of the agents
env_info = env.reset( train_mode=True )[ brain_name ]    
states = env_info.vector_observations

while True:
    
    # choose the actions we should take
    actions = agent_overlord.choose_actions( states )
    
    # apply them
    env_info = env.step( actions )[ brain_name ]
    
    next_states = env_info.vector_observations
    rewards = env_info.rewards
    dones = env_info.dones
    
    # update the overlord
    agent_overlord.step( states, actions, rewards, next_states, dones )
    
    # update states for next iteration
    states = next_states
    
    if np.any( dones ):
        print("there was a done")
        break

# print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

tensor([[-0.0724, -0.0669,  0.4784, -0.5794]], grad_fn=<AddmmBackward>)
tensor([[0.0522]], grad_fn=<AddmmBackward>)
tensor([[-0.7953,  0.7281,  1.5227, -0.5991]], grad_fn=<AddmmBackward>)
tensor([[0.5573]], grad_fn=<AddmmBackward>)
tensor([[ 1.2042, -0.0577, -0.4668,  0.8420]], grad_fn=<AddmmBackward>)
tensor([[0.2024]], grad_fn=<AddmmBackward>)
tensor([[ 0.1987, -0.0268,  0.2881,  0.6461]], grad_fn=<AddmmBackward>)
tensor([[-0.6942]], grad_fn=<AddmmBackward>)
tensor([[-0.5091,  0.6406,  0.0729, -0.4004]], grad_fn=<AddmmBackward>)
tensor([[-0.5292]], grad_fn=<AddmmBackward>)
tensor([[ 0.4758, -0.8860, -0.4612,  0.5132]], grad_fn=<AddmmBackward>)
tensor([[-0.3844]], grad_fn=<AddmmBackward>)
tensor([[-0.7467, -0.7518, -0.0390,  0.7521]], grad_fn=<AddmmBackward>)
tensor([[-0.2164]], grad_fn=<AddmmBackward>)
tensor([[ 0.3472,  0.4399, -0.1160,  0.4019]], grad_fn=<AddmmBackward>)
tensor([[0.6880]], grad_fn=<AddmmBackward>)
tensor([[ 0.0870, -0.0796, -0.2866,  0.1277]], grad_fn=<AddmmBackwar

UnityActionException: There was a mismatch between the provided action and environment's expectation: The brain ReacherBrain expected 80 continuous action(s), but was provided: [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

When finished, you can close the environment.

In [8]:
env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```